# Generated by Django 4.2.5 on 2023-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Bussiness', 'Bussiness'), ('Academy', 'Academy'), ('Other', 'Other')], max_length=20),
        ),
    ]
